definitions:
  request.BlogDetail:
    properties:
      blogImage:
        description: 文章封面
        type: string
      category:
        description: 文章类型
        type: string
      content:
        description: 文章内容
        type: string
      description:
        description: 文章简要
        type: string
      name:
        description: 博客名称
        type: string
      tag:
        description: 文章标签
        type: string
    type: object
  request.CategoryContent:
    properties:
      label:
        type: string
    type: object
  request.Login:
    properties:
      captcha:
        description: 验证码
        type: string
      captchaId:
        description: 验证码ID
        type: string
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    type: object
  request.Register:
    properties:
      enable:
        type: integer
      nickName:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  request.TagContent:
    properties:
      label:
        type: string
    type: object
  request.UpdateCategoryContent:
    properties:
      id:
        type: string
      label:
        type: string
    type: object
  request.UpdateTag:
    properties:
      id:
        description: 主键ID
        type: string
      label:
        type: string
    type: object
info:
  contact: {}
paths:
  /base/blog:
    get:
      description: 根据id获取博客详情
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: string
      responses:
        "200":
          description: '{"code": "200", "msg": "", "data": ""}'
          schema:
            type: string
      summary: 根据id获取博客详情
      tags:
      - Base
  /base/blog/list:
    get:
      description: 获取博客列表
      parameters:
      - description: 当前页
        in: query
        name: page
        required: true
        type: integer
      - description: 每页请求数量
        in: query
        name: pageSize
        required: true
        type: integer
      - description: 搜索内容
        in: query
        name: keyWord
        type: string
      responses:
        "200":
          description: '{"code": "200", "msg": "", "data": ""}'
          schema:
            type: string
      summary: 获取博客列表
      tags:
      - Base
  /base/category:
    get:
      description: 根据id获取分类详情
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: string
      responses:
        "200":
          description: '{"code": "200", "msg": "", "data": ""}'
          schema:
            type: string
      summary: 根据id获取分类详情
      tags:
      - Base
  /base/category/list:
    get:
      description: 获取分类列表
      parameters:
      - description: 当前页
        in: query
        name: page
        required: true
        type: integer
      - description: 每页请求数量
        in: query
        name: pageSize
        required: true
        type: integer
      - description: 搜索内容
        in: query
        name: keyWord
        type: string
      responses:
        "200":
          description: '{"code": "200", "msg": "", "data": ""}'
          schema:
            type: string
      summary: 获取分类列表
      tags:
      - Base
  /base/login/token:
    post:
      consumes:
      - application/json
      description: 用户登录
      parameters:
      - description: 用户名
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.Login'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": "200", "msg": "", "data": ""}'
          schema:
            type: string
      summary: 用户登录
      tags:
      - Base
  /base/register:
    post:
      consumes:
      - application/json
      description: 用户注册
      parameters:
      - description: 用户注册信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.Register'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": "200", "msg": "", "data": ""}'
          schema:
            type: string
      summary: 用户注册
      tags:
      - Base
  /base/tag:
    get:
      description: 根据id获取标签信息
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: string
      responses:
        "200":
          description: '{"code": "200", "msg": "", "data": ""}'
          schema:
            type: string
      summary: 根据id获取标签信息
      tags:
      - Base
  /base/tag/list:
    get:
      description: 获取标签列表
      responses:
        "200":
          description: '{"code": "200", "msg": "", "data": ""}'
          schema:
            type: string
      summary: 获取标签列表
      tags:
      - Base
  /blog/add:
    post:
      consumes:
      - application/json
      description: 新增博客
      parameters:
      - description: 博客信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.BlogDetail'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": "200", "msg": "", "data": ""}'
          schema:
            type: string
      summary: 新增博客
      tags:
      - 博客管理
  /blog/delete:
    delete:
      description: 删除博客
      parameters:
      - description: 当前页
        in: query
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: '{"code": "200", "msg": "", "data": ""}'
          schema:
            type: string
      summary: 删除博客
      tags:
      - 博客管理
  /category/add:
    post:
      consumes:
      - application/json
      description: 添加分类
      parameters:
      - description: 分类信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.CategoryContent'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": "200", "msg": "", "data": ""}'
          schema:
            type: string
      summary: 添加分类
      tags:
      - 分类管理
  /category/delete:
    delete:
      description: 删除分类
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: string
      responses:
        "200":
          description: '{"code": "200", "msg": "", "data": ""}'
          schema:
            type: string
      summary: 删除分类
      tags:
      - 分类管理
  /category/update:
    put:
      consumes:
      - application/json
      description: 更新分类
      parameters:
      - description: 分类信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.UpdateCategoryContent'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": "200", "msg": "", "data": ""}'
          schema:
            type: string
      summary: 更新分类
      tags:
      - 分类管理
  /tag/add:
    post:
      consumes:
      - application/json
      description: 添加标签
      parameters:
      - description: 标签信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.TagContent'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": "200", "msg": "", "data": ""}'
          schema:
            type: string
      summary: 添加标签
      tags:
      - 标签管理
  /tag/delete:
    delete:
      description: 删除标签
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: string
      responses:
        "200":
          description: '{"code": "200", "msg": "", "data": ""}'
          schema:
            type: string
      summary: 删除标签
      tags:
      - 标签管理
  /tag/update:
    put:
      consumes:
      - application/json
      description: 更新标签
      parameters:
      - description: 标签信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.UpdateTag'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": "200", "msg": "", "data": ""}'
          schema:
            type: string
      summary: 更新标签
      tags:
      - 标签管理
  /user/list:
    get:
      description: 获取用户列表
      parameters:
      - description: 当前页
        in: query
        name: page
        required: true
        type: integer
      - description: 每页请求数量
        in: query
        name: pageSize
        required: true
        type: integer
      - description: 搜索内容
        in: query
        name: keyWord
        type: string
      responses:
        "200":
          description: '{"code": "200", "msg": "", "data": ""}'
          schema:
            type: string
      summary: 获取用户列表
      tags:
      - 用户管理
  /user/me:
    get:
      description: 获取用户信息
      responses:
        "200":
          description: '{"code": "200", "msg": "", "data": ""}'
          schema:
            type: string
      summary: 获取用户信息
      tags:
      - 用户管理
swagger: "2.0"
